### ISSUE TITLE
关于模型复现的问题

### ISSUE THREAD

**Issue by MarchenCreator** [HKUDS/GraphEdit#10]
感谢您的代码分享！

我在复现GraphEdit的时候遇到了一些问题：请问节点嵌入是如何获取的？论文中写的似乎是一个冻结的嵌入模型，但是代码中我没有看到除了vicuna之外的东西？请问是直接用节点的raw_text直接嵌入的吗，有没有使用一些的prompt引导回答之类的方法？

另外我注意到，我使用llama3-8b来进行边预测，它的效果似乎很差，vicuna的lora是特别适合执行这类任务的微调吗

**Comment by LarFii** [comment]
非常感谢您的关注！

节点的嵌入我们是直接根据节点的raw_text然后利用vicuna提供的词表得到的。另外如果想用llama3-8b进行边预测，需要先微调让它理解这个任务。另一方面llama3-8b可能需要使用instruct版本。

还有什么疑问欢迎您继续提问！

**Comment by MarchenCreator** [comment]
好的，非常感谢您的解答！我已经下载了instruct版本准备下一步尝试。

另外，我用vicuna-7b复现的时候，cora上仅仅达到了89.3左右的acc，所以关于微调和预测我还有一些疑问想麻烦和您确认一下：

1.我看您的train_edge_predictor.py似乎是用来构建一个两层的全连接层来给边打分，这里的数据集构建是仅用了训练集中有的边吗？还是在训练集中随机抽样节点对，如果标签一样就是正例，否则是反例？

2.类似的，在微调LLM的数据集中，微调语料是基于edge_index中已存在的边还是从训练集中随机生成的节点对，是否需要控制正负样本的比例？虽然我注意到create_ins.py中的 for index in trange(len(data.edge_index[0]))  但是这样的数据量足够吗

3.我看您要求LLM如果信息不全，就输出True，但是create_ins.py中的构建似乎不管信息是否完整，只要是同质，均result = f"True. {data.category_names[paperID_0]}."这是为啥？

期待您的回复

**Comment by LarFii** [comment]
对于cora的性能，目前predict_edge中的k值默认设置成3，而不同k值的候选边数量会对性能造成一定影响，可以参考论文中4.4节。
对于第1个问题，train_edge_predictor.py的训练集与微调语料一致。
对于第2个问题，微调语料是从训练集中随机生成的节点对，采用的正负比例是2:1。create_ins.py是用来处理edge_predictor预测的候选边，将其变为自然语言形式。
对于第3个问题，信息不完整的情况主要出现在Cora中，instruction模版可以参考[3.instruction-template](https://github.com/HKUDS/GraphEdit/tree/main?tab=readme-ov-file#3-instruction-template)，可以根据自己的数据集情况构建训练集。

**Comment by MarchenCreator** [comment]
好的，感谢您的回复，也就是说仅仅在cora的微调语料中，才会出现仅有True而没有分类的回答，作为指令微调模板是吗？

**Comment by LarFii** [comment]
是的是的，感谢您的关注。

**Comment by MarchenCreator** [comment]
好的，谢谢您，所以cora_template_sample应该是用LLM筛选MLP选出的边用的json，那么cora_template是否是微调语料？

**Comment by LarFii** [comment]
cora_template_sample是我们的微调预料，cora_template则是cora中的原始边，[Stage-2](https://github.com/HKUDS/GraphEdit?tab=readme-ov-file#stage-2-get-the-candidate-structure)中提供了edge_predictor，可以用它生成候选边{dataset}\_edges_add\_{topK}.json，[Stage-4](https://github.com/HKUDS/GraphEdit?tab=readme-ov-file#stage-4-eval-the-refined-structure)中则提供了最终结果。

**Comment by MarchenCreator** [comment]
好的，非常感谢您的解答！
