### ISSUE TITLE
File is missing. Thank you for your answer!

### ISSUE THREAD

**Issue by linxuequan** [HKUDS/GraphEdit#11]
Excuse me, the X_template_add_X.npy in the result2np.py is missing. Can I replace X_edges_add_X.npy with X_template_add_X.npy? Thank you.

**Comment by LarFii** [comment]
Thank you for your interest in GraphEdit!

Sorry, I just saw this issue. I made a mistake, the X_template_add_X.npy in the result2np.py actually is X_edges_add_X.npy. I have corrected it. Thanks!
