### ISSUE TITLE
Data file

### ISSUE THREAD

**Issue by Roiko97** [HKUDS/GraphEdit#12]
Dear authors,
When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?

Thank you very much!

**Comment by Andy3117006664** [comment]
> Dear authors, When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?
> 
> Thank you very much!

And do you konw how the '_fixed_tfidf.pt' files are obtained？

**Comment by Roiko97** [comment]
> > Dear authors, When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?
> > Thank you very much!
> 
> And do you konw how the '_fixed_tfidf.pt' files are obtained？

This file  is available at   https://github.com/CurryTang/Graph-LLM.

**Comment by LarFii** [comment]
> Dear authors, When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?
> 
> Thank you very much!

Thanks for your interest! 

The cora_template_sample.json samples from Cora, but it is not generated by LLM/graphedit/data/sample.py. We sample the labeled node pairs in the Cora and set whether there is a connection based on the consistency of the labels. The positive and negative sampling ratio is 2:1. For the Cora, we additionally consider the situation where text is missing. For any node in a node pair where text is missing, we set the connection label as True.

**Comment by LarFii** [comment]
> > Dear authors, When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?
> > Thank you very much!
> 
> And do you konw how the '_fixed_tfidf.pt' files are obtained？

The data can get from [1. Download TAG datasets](https://github.com/HKUDS/GraphEdit/tree/main#1-download-tag-datasets)

**Comment by Roiko97** [comment]
> > Dear authors, When considering the Cora dataset, could you please clarify how cora_template.json is obtained? Additionally, I guess that cora_template_sample.json is generated by LLM/graphedit/data/sample.py, am I correct?
> > Thank you very much!
> 
> Thanks for your interest!
> 
> The cora_template_sample.json samples from Cora, but it is not generated by LLM/graphedit/data/sample.py. We sample the labeled node pairs in the Cora and set whether there is a connection based on the consistency of the labels. The positive and negative sampling ratio is 2:1. For the Cora, we additionally consider the situation where text is missing. For any node in a node pair where text is missing, we set the connection label as True.

Thank you so much for your response. 

Can I find the relevant code for generating cora_template.json and cora_template_sample.json in this repository?

**Comment by LarFii** [comment]
Sorry, no code can be used directly, but it can be modified according to LLM/scripts/create_ins.py, and the template is the same. More instruction templates can be found in [3. Instruction Template
](https://github.com/HKUDS/GraphEdit/tree/main?tab=readme-ov-file#3-instruction-template)

**Comment by Roiko97** [comment]
> Sorry, no code can be used directly, but it can be modified according to LLM/scripts/create_ins.py, and the template is the same. More instruction templates can be found in [3. Instruction Template ](https://github.com/HKUDS/GraphEdit/tree/main?tab=readme-ov-file#3-instruction-template)

Thank you so much for your response  : )
