### ISSUE TITLE
Encountering problems in reproducing

### ISSUE THREAD

**Issue by xms66** [HKUDS/GraphEdit#2]
<img width="707" alt="1710768939415" src="https://github.com/HKUDS/GraphEdit/assets/105098116/d27af0f4-ac1e-4640-80bb-3b97cbcb007f">
 我按照指示从huggingface中下载vicuna7b，并放到下图所示的位置
<img width="473" alt="1710769763583" src="https://github.com/HKUDS/GraphEdit/assets/105098116/f585b410-ab41-4ca8-8479-d40c38b79086">

当我执行sh scripts/train_lora.sh时，遇到了这样的报错：
<img width="1151" alt="1710769864125" src="https://github.com/HKUDS/GraphEdit/assets/105098116/29af8d15-c991-4459-9070-3ae45b8a7d66">

**Comment by LarFii** [comment]
可以试试换成相对路径，例如 ./scripts/vicuna7b

**Comment by Pzx-Doctom** [comment]
![image](https://github.com/HKUDS/GraphEdit/assets/55266625/fb05f87e-9a4a-46f2-85e1-63b830b015cd)
您好，请问程序在试图解析和使用DeepSpeed的配置文件时出现了问题是啥情况呢（环境是用您提供的打包好的）？对您的工作非常感兴趣，谢谢

**Comment by xms66** [comment]
> 可以试试换成相对路径，例如 ./scripts/vicuna7b

还是一样的报错
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./scripts/vicuna7b.
