### ISSUE TITLE
question about adversarial robustness experiment

### ISSUE THREAD

**Issue by zhongjian-zhang** [HKUDS/GraphEdit#3]
Hi, I have a question on "Model Robustness Study against Noise". 

1. Which attack method is used in the experiment?
2. Did the attack occur during the training phase or the testing phase?
 
Looking forward your reply! Best wish!

**Comment by LarFii** [comment]
Thanks for your interest.
For the questions:
  1. We use random noise in the experiment by injecting noisy edges into the original graph structure at different rates.
  2. After training the GraphEdit, we inject noise and use the trained GraphEdit to denoise before the GNN training.
