### ISSUE TITLE
关于embedding_dim，我想请问一下为什么维度会设置这么大？

### ISSUE THREAD

**Issue by zhuiyue233** [HKUDS/GraphEdit#5]
parser = argparse.ArgumentParser()
  parser.add_argument('--device', type=str, default='cuda')
  parser.add_argument('--dataset', type=str, default='pubmed')
  parser.add_argument('--top_k', type=int, default=3)
  parser.add_argument('--embedding_dim', type=int, default=4096)
  parser.add_argument('--batch_size', type=int, default=8192)
  parser.add_argument('--hidden_dim', type=int, default=1024)
  parser.add_argument('--combine', type=bool, default=False)
  
  这个embedding_dim默认4096，hidden_dim是1024

**Comment by LarFii** [comment]
这个是follow的[FastChat](https://github.com/lm-sys/FastChat)的默认设置
