### ISSUE TITLE
关于LLM-Enhanced Structure Refinement 

### ISSUE THREAD

**Issue by B1uee** [HKUDS/GraphEdit#6]
您好，首先感谢您的代码开源。

我在阅读论文时就有一个疑惑，

> ”These instructions include the task of predicting both the existence of edges and the specific category of connected nodes.“

我不是很理解为什么用table_1给出的prompt还能实现对边的处理，特别是在stage_3做refine时，应该是利用训练好的LLM对合并后的A'做剪枝操作，是怎么基于那段prompt实现的呢？

**Comment by B1uee** [comment]
主要是我在edge_predictor看到了单纯的增边操作，但在剪枝时似乎没有专门训练一个分类器？

**Comment by B1uee** [comment]
> 您好，首先感谢您的代码开源。
> 
> 我在阅读论文时就有一个疑惑，
> 
> > ”These instructions include the task of predicting both the existence of edges and the specific category of connected nodes.“
> 
> 我不是很理解为什么用table_1给出的prompt还能实现对边的处理，特别是在stage_3做refine时，应该是利用训练好的LLM对合并后的A'做剪枝操作，是怎么基于那段prompt实现的呢？

我后续看到了[result2np.py](https://github.com/HKUDS/GraphEdit/blob/main/LLM/scripts/result2np.py)，最后一个问题是：您提出的这个图结构优化的方法，特别是delete的部分，对除分类以外的下游任务的泛化性大概如何呢？

**Comment by LarFii** [comment]
感谢您对我们工作的关注！我们目前的工作主要针对节点分类任务展开，未来我们计划进一步研究，将这一方法应用于其他下游任务，以确保其更广泛的适用性和泛化性。
