### ISSUE TITLE
关于cora_text.npy的内容是否是和raw中的顺序一一对应

### ISSUE THREAD

**Issue by MarchenCreator** [HKUDS/GraphEdit#7]
非常感谢您公开代码！
我在进行相关实验的时候遇到了一些问题， 想确认一下原始数据中(从您提供谷歌网盘下载)的cora_text.npy文件中记录的应该是论文的标题和摘要，它们看起来是用冒号分割开的
我想问一下该文件这个顺序是否和数据集中cora.x cora.y的顺序一样，是一一对应的？

**Comment by LarFii** [comment]
感谢您的关注！
cora_text.npy是从cora_fixed_tfidf.pt中提取出来的，和cora_fixed_tfidf.pt中的x，y是一一对应的。实验中也都是采用的cora_fixed_tfidf.pt中的数据。细节可以在GraphEdit/GNN/datasets/load_cora.py中看到。

**Comment by MarchenCreator** [comment]
谢谢您的解答，我找到我的问题了，我使用torch.load加载后正确读取了数据集。
另外我发现cora等数据集似乎存在部分摘要和标题的缺失，这是否是正常的？

**Comment by LarFii** [comment]
> 谢谢您的解答，我找到我的问题了，我使用torch.load加载后正确读取了数据集。 另外我发现cora等数据集似乎存在部分摘要和标题的缺失，这是否是正常的？

是的，这是正常现象，会存在一定的缺失

**Comment by MarchenCreator** [comment]
感谢您的解答。
